name: 'Deploy API to Azure'

on: 
  push:
    branches:
      - main
jobs:
  build_templates: 
    name: Build ARM templates from yaml
    runs-on: windows-latest
    env:
      APIM_RESOURCE_KIT_URI: 'https://github.com/Azure/azure-api-management-devops-resource-kit/archive/refs/heads/master.zip'
      EXTRACTED_PROJECT_PATH: '.\apim_rk\extracted\azure-api-management-devops-resource-kit-master\src\ArmTemplates\ArmTemplates.csproj'
    steps:
      - uses:  actions/checkout@v1
      - name: Setup dotnet '6.0.x'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Download latest APIM Resource Kit
        shell: pwsh
        run: |
          mkdir apim_rk
          cd apim_rk
          mkdir extracted
          Invoke-WebRequest ${{env.APIM_RESOURCE_KIT_URI}} -outfile .\archive.zip
          Expand-Archive -LiteralPath ".\archive.zip" -DestinationPath ".\extracted" -Force
          cd ..
          mkdir templates
      - name: Generate the ARM templates using the tool
        run: dotnet run create --configFile api.yaml template/
      - name: Upload the built ARM templates
        uses: actions/upload-artifact@main
        with:
          name: armtemplates
          path: template
         
      
  deploy_templates:
    name: Deploy ARM templates
    needs: build_templates
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@main
        name: Download Templates
        with: 
          name: armtemplates
          path: templates
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      - name: Deploy the Backends
        run: az deployment group create -g ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file ".\templates\mfapim-backends.template.json" --parameters ApimServiceName=${{ secrets.AZURE_APIM_NAME }}
      - name: Deploy the API
        run: az deployment group create -g ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file ".\templates\ICanHazDadJoke.api.template.json" --parameters ApimServiceName=${{ secrets.AZURE_APIM_NAME }}
      - name: Azure logout
        run: az logout
  verify_api:
    name: Test the APIs
    needs: deploy_templates
    runs-on: ubuntu-latest
    steps:
      - name: Call Single API
        run: |
          STATUSCODE=$(curl --silent --output /dev/stderr --write-out "%{http_code}" --request GET --url ${{ secrets.AZURE_APIM_BASE_URL }} --header 'ocp-apim-subscription-key: ${{ secrets.AZURE_APIM_SUBSCRIPTION_KEY }}')
          if test $STATUSCODE -ne 200; then
            exit 1
          fi
      - name: Call Search API
        run: |
          STATUSCODE=$(curl --silent --output /dev/stderr --write-out "%{http_code}" --request POST --url "${{ secrets.AZURE_APIM_BASE_URL }}/search" --header 'content-type: application/json' --header 'ocp-apim-subscription-key: ${{ secrets.AZURE_APIM_SUBSCRIPTION_KEY }}' --data '{"term" : "cat","page" : 1,"limit" : 5}')
          if test $STATUSCODE -ne 200; then
            exit 1
          fi
      
      

